# Generated by Django 5.0.1 on 2024-08-26 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UploadedFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('size', models.BigIntegerField()),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FileChunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chunk_number', models.IntegerField()),
                ('total_chunks', models.IntegerField()),
                ('chunk_data', models.BinaryField()),
                ('file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.uploadedfile')),
            ],
            options={
                'unique_together': {('file', 'chunk_number')},
            },
        ),
    ]
